version: "3.9"

services:
  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "5001:5000"
    networks:
      - spray_network

  formation-service:
    build: ./backend/formation-service
    container_name: formation-service
    ports:
      - "5002:5000"
    networks:
      - spray_network

  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    ports:
      - "5003:5000"
    networks:
      - spray_network

  order-service:
    build: ./backend/order-service
    container_name: order-service
    ports:
      - "5004:5000"
    networks:
      - spray_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - formation-service
      - payment-service
      - order-service
    networks:
      - spray_network

networks:
  spray_network:
    driver: bridge
